config/routes.rb
OriginsDeckB::Application.routes.draw do
  resources :champions

  get "home/index"

  root :to => 'home#index'

end

app/models/champion.rb
class Champion < ActiveRecord::Base
  attr_accessible :ability, :attack, :aura, :card_number, :disciplines, :energy, :factions, :health, :name, :rarity, :set_id

  # TODO:  This should probably live in a module in lib
  DISCIPLINES = %w(fighter caster summoner)
  FACTIONS = %w(phage)

  %w(factions disciplines).each do |meth|
    define_method(meth) do
       JSON.parse(self.send("#{meth}_json".to_sym))
    end
    define_method("#{meth}=") do |val|
      self.send("#{meth}_json=".to_sym, JSON.generate(val))
    end
  end

  # Helper methods
  DISCIPLINES.each do |discipline|
    define_method("#{discipline}?") do
      disciplines.include? discipline
    end
  end

  FACTIONS.each do |faction|
    define_method("#{faction}?") do
      factions.include? faction
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @champions }
    end
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
    @champion = Champion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @champion }
    end
  end

  # GET /champions/new
  # GET /champions/new.json
  def new
    @champion = Champion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @champion }
    end
  end

  # GET /champions/1/edit
  def edit
    @champion = Champion.find(params[:id])
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(params[:champion])

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render json: @champion, status: :created, location: @champion }
      else
        format.html { render action: "new" }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /champions/1
  # PUT /champions/1.json
  def update
    @champion = Champion.find(params[:id])

    respond_to do |format|
      if @champion.update_attributes(params[:champion])
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion = Champion.find(params[:id])
    @champion.destroy

    respond_to do |format|
      format.html { redirect_to champions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awareness_helper.rb
module AwarenessHelper
  def set_methods(awareness)
    # TODO: This should be in an actual class.  I'm just hella-lazy
    def awareness.is_focal?(spot)
      self[:focal] == spot
    end

    def awareness.is_summoning?(spot)
      self[:summon_spots].include? spot
    end

    def awareness.is_casting?(spot)
      self[:casting_spots].include? spot
    end

    def awareness.is_attacking?(spot)
      self[:attack_spots].include? spot
    end
  end

  def classes_for_square(spot, awareness)
    classes = ['square']
    classes << 'focal' if awareness.is_focal?(spot)
    classes << 'summon' if awareness.is_summoning?(spot)
    classes << 'casting' if awareness.is_casting?(spot)
    classes << 'attack' if awareness.is_attacking?(spot)
    classes
  end

  # Greek Symbols:  http://ancienthistory.about.com/od/greeklanguage/a/ASCIIGreek.htm
  def focal
    "&#916;".html_safe # Delta / Δ
  end

  def casting
    "&#927;".html_safe # Omicron / O
  end

  def attack
    "&#935;".html_safe # Chi / X
  end
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/awareness/_grid.html.haml
-# TODO: This should be in an actual class.  I'm just hella-lazy
- awareness = {height: 3, width: 3, focal: [1, 1], summon_spots: [[0,1], [1,2], [2,1]], casting_spots: [[1,2]], attack_spots: [[1,2]]}
- set_methods(awareness)

- height = awareness[:height] - 1
- width = awareness[:width] - 1
%table
  - (0..height).to_a.reverse.each do |y|
    %tr
      - (0..width).each do |x|
        - spot = [x, y]
        %td{:class => classes_for_square(spot, awareness)}
          - if awareness.is_focal?(spot)
            %span= focal
          - if awareness.is_casting?(spot)
            %span= casting
          - if awareness.is_attacking?(spot)
            %span= attack

app/views/champions/_form.html.haml
= form_for @champion do |f|
  - if @champion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@champion.errors.count, "error")} prohibited this champion from being saved:"
      %ul
        - @champion.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :attack
    = f.number_field :attack
  .field
    = f.label :aura
    = f.number_field :aura
  .field
    = f.label :energy
    = f.number_field :energy
  .field
    = f.label :health
    = f.number_field :health
  .field
    = f.label :ability
    = f.text_area :ability
  = render 'shared/factions_input'
  = render 'shared/disciplines_input'
  .field
    = f.label :set_id
    = f.number_field :set_id
  .field
    = f.label :card_number
    = f.number_field :card_number
  .field
    = f.label :rarity
    = f.text_field :rarity
  .actions
    = f.submit 'Save'

app/views/champions/edit.html.haml
%h1 Editing champion

= render 'form'

= link_to 'Show', @champion
\|
= link_to 'Back', champions_path

app/views/champions/index.html.haml
%h1 Listing champions

%table
  %tr
    %th Name
    %th Attack
    %th Aura
    %th Energy
    %th Health
    %th Ability
    %th Factions
    %th Disciplines
    %th Set
    %th Card number
    %th Rarity
    %th
    %th
    %th

  - @champions.each do |champion|
    %tr
      %td= champion.name
      %td= champion.attack
      %td= champion.aura
      %td= champion.energy
      %td= champion.health
      %td= champion.ability
      %td= champion.factions
      %td= champion.disciplines
      %td= champion.set_id
      %td= champion.card_number
      %td= champion.rarity
      %td= link_to 'Show', champion
      %td= link_to 'Edit', edit_champion_path(champion)
      %td= link_to 'Destroy', champion, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Champion', new_champion_path

app/views/champions/new.html.haml
%h1 New champion

= render 'form'

= link_to 'Back', champions_path

app/views/champions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @champion.name
%p
  %b Attack:
  = @champion.attack
%p
  %b Aura:
  = @champion.aura
%p
  %b Energy:
  = @champion.energy
%p
  %b Health:
  = @champion.health
%p
  %b Ability:
  = @champion.ability
%p
  %b Factions:
  = @champion.factions
%p
  %b Disciplines:
  = @champion.disciplines
%p
  %b Set:
  = @champion.set_id
%p
  %b Card number:
  = @champion.card_number
%p
  %b Rarity:
  = @champion.rarity

= link_to 'Edit', edit_champion_path(@champion)
\|
= link_to 'Back', champions_path

app/views/home/index.html.haml
%h1 Home#index

%p
  Find me in app/views/home/index.html.erb


- current_user = "Assad"

%ul
  %li first item
  %li second item
  %li
    %b= "Hi #{current_user}, you are #{20 * 3} points away!"

= render('awareness/grid')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OriginsDeckB</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_disciplines_input.html.haml
.field
  %u Disciplines
  -# TODO: Check out _factions_input.html.haml to see a metaprogramming way to do this.
    The way it is done in factions makes it easier to add new ones
  %br
  = label_tag 'fighter_discipline', 'Fighter'
  = check_box_tag 'fighter_discipline', 'fighter', @champion.fighter?, :name => 'champion[disciplines][]'
  %br
  = label_tag 'caster_discipline', 'Caster'
  = check_box_tag 'caster_discipline', 'caster', @champion.caster?, :name => 'champion[disciplines][]'
  %br
  = label_tag 'summoner_discipline', 'Summoner'
  = check_box_tag 'summoner_discipline', 'summoner', @champion.summoner?, :name => 'champion[disciplines][]'

app/views/shared/_factions_input.html.haml
.field
  %u Factions
  - Champion::FACTIONS.each do |faction|
    %br
    = label_tag "#{faction}_faction", faction.capitalize
    = check_box_tag "#{faction}_faction", faction, @champion.send("#{faction}?"), :name => 'champion[factions][]'